# flake8: noqa E501

from django.conf import settings
from groq import Groq


class GroqService:
    messages = [
        {
            "role": "system",
            "content": "You are a large language model trained on a massive dataset of tax documents and financial information."
            + " You can access and process anonymized W2 data to answer user queries about their income, taxes withheld, and other relevant details."
            + " You can understand natural language questions and respond in a clear, concise, and informative way."
            + " You prioritize data privacy and security, ensuring that no sensitive information is revealed in your responses."
            + " You should hide any sensitive information such as social security numbers, addresses, or other personal details.",
        }
    ]

    def __init__(self, messages=[]):
        self.client = Groq(
            api_key=settings.GROQ_API_KEY,
        )

        self.messages = self.messages + messages

    def complete_chat_message(self, message):
        """
        Completes a chat message using Groq.

        Args:
            message_content (str): The content of the chat message.

        Returns:
            str: The completion message generated by Groq.

        """
        self.messages.append({"role": "user", "content": message})

        chat_completion = self.client.chat.completions.create(
            messages=self.messages,
            model="llama3-8b-8192",
            temperature=1,
            max_tokens=1024,
            top_p=1,
            stop=None,
            stream=False,
        )

        completion_message = chat_completion.choices[0].message.content

        self.messages.append({"role": "assistant", "content": completion_message})

        return completion_message
