[tool.black]
line-length = 120
target-version = ['py312']
include = '\.pyi?$'
exclude = '''
/(
    \.toml
  | \.sh
  | \.git
  | \.ini
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | Jenkinfile
  | migrations
)/
'''

[tool.docformatter]
black=true
wrap-summaries=80
wrap-descriptions=80
pre-summary-newline=true
make-summary-multi-line=true
close-quotes-on-newline=true
blank=true
