# Generated by Django 5.0.4 on 2024-04-30 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="image",
        ),
    ]
